INSERT INTO category (description) VALUES ('American') ;
INSERT INTO category (description)  VALUES ('Mexican') ;
INSERT INTO category (description)  VALUES ('Italian') ;
INSERT INTO category (description)  VALUES ('Turkish') ;
INSERT INTO category (description)  VALUES ('Fast Food') ;
INSERT INTO unit_of_measure (description)  VALUES ('Teaspoon') ;
INSERT INTO unit_of_measure (description)  VALUES ('Tablespon') ;
INSERT INTO unit_of_measure (description)  VALUES ('Cup') ;
INSERT INTO unit_of_measure (description)  VALUES ('Pinch') ;
INSERT INTO unit_of_measure (description)  VALUES ('Tutam') ;
INSERT INTO unit_of_measure (description)  VALUES ('Quence') ;
INSERT INTO unit_of_measure (description)  VALUES ('Each') ;
INSERT INTO unit_of_measure (description)  VALUES ('Dash') ;
INSERT INTO unit_of_measure (description)  VALUES ('Pint') ;
